# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9214df2033ec33f81d2683d72e77b2067391f26ea1899c1df41d6e276526783ee97535115683ce92b6c9501432c49f7731b24564d50c752619222292febfda

test:
  secret_key_base: 0f4d5fc55bc0b55e9eb9e5049571d5cf9157976af899041aaf6e7cfe95779ba37bfe16bdbfd8f98297ceee738072519baa27077faa5321488b5a78653b40db49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
